title: "Nextcloud Custom Install"
description: "Dokumentasi setup Nextcloud di CasaOS (Docker + PostgreSQL + Redis + Cloudflare Tunnel) dengan troubleshooting dan checklist."
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme

color_scheme: dark
search_enabled: true
heading_anchors: true
back_to_top: true
back_to_top_text: "Back to top"

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    block:
      line_numbers: false

aux_links:
  "Repo":
    - "https://github.com/mohammadisa2/NextcloudCustomImage"
